dist: xenial
env:
  global:
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH
language: node_js
node_js:
  - 'stable'
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - sudo pip install --upgrade pip
  - pip install awscli

install:
  - npm install

script:
  # - npm run cypress
  - npm run build
  - npm run deploy-s3
